### PR TITLE
Initial commit for the 80rave theme :tada: :lipstick:

### PR DESCRIPTION
**Pull request by PetrBarborka**
Note: I have tried to produce the screenshot in the format you use, but I haven't found a way to do it exactly - so at least I provided output from the colortest-16. Cheers

* [x] Put an `x` between the brackets on this line if you have done all of the following things:
  * Create a new file name `your-scheme-name.js` under [scheme](https://github.com/ooJerryLeeoo/hyper-material-box/tree/master/scheme) folder
  * The code format look like this:
  ``` javascript
  'use strict';

  module.exports = {
    colors: {
      black: '...',
      red: '...',
      green: '...',
      yellow: '...',
      blue: '...',
      magenta: '...',
      cyan: '...',
      white: '...',
      lightBlack: '...',
      lightRed: '...',
      lightGreen: '...',
      lightYellow: '...',
      lightBlue: '...',
      lightMagenta: '...',
      lightCyan: '...',
      lightWhite: '...',
    },

    // Default
    backgroundColor: '...',
    foregroundColor: '...',
    cursorColor: '...',
    borderColor: '...',

    // Accent color
    accentColor: '...',

    // Other (optional, it will be override by foregroundColor)
    inactiveTabTitleColor: '...',
    activeTabTitleColor: '...',

    // css (optional)
    css: '...',
    termCSS: '...',
  };
  ```
  * Add your color scheme to the :point_right: [schemeIndex](https://github.com/ooJerryLeeoo/hyper-material-box/blob/master/index.js#L3) (**ALPHABETICAL** order)
  * Add your color scheme to the `README.md` list (**ALPHABETICAL** order)
  * Add your color scheme to the :point_right: [keywords](https://github.com/ooJerryLeeoo/hyper-material-box/blob/master/package.json#L6) (**ALPHABETICAL** order)

### CODE REVIEW

**Comment by jerrykal** [comment]
@PetrBarborka Thank you for the contributing :heart:. 

Could you remove the `activateTabStyle`, `highlightActiveTab` and `lightEffect` from the `80rave.js` ?? thanks :+1:

**Comment by PetrBarborka** [comment]
Done. Offtopic: How do I make the color palette screenshot like you do? Thx

**Comment by jerrykal** [comment]
@PetrBarborka Well, I use [this](https://gist.github.com/ooJerryLeeoo/7e122872733801185f6ed9e46c34c98f) shell script.
Don't worry about the screenshot, I'll do it my self 👍

**Comment by jerrykal** [comment]
@PetrBarborka Ok, last change requests: change the `**26**` to `**27**` from `README.md`, I forgot to put it in the PR template, sorry...

**Comment by PetrBarborka** [comment]
Well, could have thought of that myself... :D

**Comment by jerrykal** [comment]
Merged, thanks :zap:

**Comment by PetrBarborka** [comment]
:+1:

**Comment by jerrykal** [comment]
@PetrBarborka I've finished the screenshot of your [80rave](https://github.com/ooJerryLeeoo/hyper-material-box/blob/master/assets/scheme/80rave.png) and add it to the [gif](https://github.com/ooJerryLeeoo/hyper-material-box/blob/master/assets/top.gif) :tada:

**Comment by PetrBarborka** [comment]
Great, thank you. Hopefully someone will find it uselful. All the other themes were too little saturated and not crazy enough for my taste :rofl:

**Pull request merged**
